
name: Sync to S3

on:
  push:
    branches:
      - main
jobs:
  
  s3-sync:    
    runs-on: ubuntu-latest
    
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          aws-region: us-east-1
      
      - name: Sync files to S3
        run: |
          # The 'aws s3 sync' command efficiently transfers files.
          # It only copies new or modified files.
          #
          # Arguments:
          #   '.': The source directory (the root of your repository).
          #   's3://your-bucket-name': The destination S3 bucket.
          #     - IMPORTANT: Replace 'your-bucket-name' with your actual bucket name.
          #   '--delete': This flag is optional. It removes files from the S3 bucket
          #               that are no longer present in your repository.
          aws s3 sync . s3://edgelinkconsult --delete
